### task 1



In [2]:
import numpy as np
vector = np.arange(10, 50)
print("Vector:", vector)

Vector: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### task 2

In [3]:
matrix = np.arange(9).reshape(3, 3)
print("3x3 Matrix:\n", matrix)

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


### task 3


In [4]:
identity_matrix = np.eye(3)
print("\nIdentity Matrix:\n", identity_matrix)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### task 4

In [12]:
random_array = np.random.random((3, 3, 3))
print("\n3x3x3 Random Array:\n", random_array)


3x3x3 Random Array:
 [[[0.29889717 0.41826074 0.48823202]
  [0.06883792 0.88024079 0.14017503]
  [0.37603417 0.99537867 0.38763361]]

 [[0.6994012  0.761524   0.59627965]
  [0.42762875 0.96020315 0.19477442]
  [0.61201927 0.08445299 0.10607261]]

 [[0.34156078 0.54198042 0.260319  ]
  [0.84512176 0.52939166 0.65153894]
  [0.44754797 0.5308415  0.72356029]]]


### task 5

In [13]:
random_matrix = np.random.random((10, 10))
min_val = np.min(random_matrix)
max_val = np.max(random_matrix)
print("\nMin value:", min_val, "Max value:", max_val)


Min value: 0.0042333918951253935 Max value: 0.9970825564921059


### task 6

In [14]:
random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print("\nMean value of random vector:", mean_value)


Mean value of random vector: 0.4005883806019369


### task 7

In [15]:
random_matrix_5x5 = np.random.random((5, 5))
normalized_matrix = (random_matrix_5x5 - np.min(random_matrix_5x5)) / (np.max(random_matrix_5x5) - np.min(random_matrix_5x5))
print("\nNormalized 5x5 Matrix:\n", normalized_matrix)


Normalized 5x5 Matrix:
 [[0.70778858 0.36592942 0.8665513  0.81809645 0.14365784]
 [0.25805653 0.33679822 0.68248739 0.24824502 0.8756067 ]
 [0.98915236 0.36012459 0.3055607  1.         0.83564072]
 [0.20984645 0.38358363 0.         0.67284929 0.11855902]
 [0.94562245 0.87951952 0.25557514 0.58913248 0.48723146]]


### task 8


In [16]:
matrix_a = np.random.randint(0, 10, (5, 3))
matrix_b = np.random.randint(0, 10, (3, 2))
matrix_product = np.dot(matrix_a, matrix_b)
print("\nMatrix Product (5x3 * 3x2):\n", matrix_product)


Matrix Product (5x3 * 3x2):
 [[65 84]
 [90 94]
 [12 11]
 [35 42]
 [43 46]]


### task 9

In [17]:
matrix_x = np.random.randint(0, 10, (3, 3))
matrix_y = np.random.randint(0, 10, (3, 3))
dot_product = np.dot(matrix_x, matrix_y)
print("\nDot Product of two 3x3 matrices:\n", dot_product)



Dot Product of two 3x3 matrices:
 [[100 161 139]
 [ 69 108  96]
 [ 33  66  62]]


### task 10

In [18]:
matrix_4x4 = np.random.randint(0, 10, (4, 4))
transpose_matrix = np.transpose(matrix_4x4)
print("\nTranspose of 4x4 matrix:\n", transpose_matrix)


Transpose of 4x4 matrix:
 [[7 9 5 1]
 [8 9 2 4]
 [0 7 8 4]
 [0 1 1 7]]


### task 11

In [19]:
matrix_3x3 = np.random.randint(0, 10, (3, 3))
determinant = np.linalg.det(matrix_3x3)
print("\nDeterminant of 3x3 matrix:", determinant)


Determinant of 3x3 matrix: 270.00000000000006


### task 12

In [20]:
matrix_A = np.random.randint(0, 10, (3, 4))
matrix_B = np.random.randint(0, 10, (4, 3))
matrix_AB = np.dot(matrix_A, matrix_B)
print("\nMatrix Product (3x4 * 4x3):\n", matrix_AB)



Matrix Product (3x4 * 4x3):
 [[104  81  55]
 [171 155  92]
 [ 64  66  35]]


### task 13

In [22]:
matrix_3x3 = np.random.randint(0, 10, (3, 3))
vector_3x1 = np.random.randint(0, 10, (3, 1))
matrix_vector_product = np.dot(matrix_3x3, vector_3x1)
print("\nMatrix-Vector Product:\n", matrix_vector_product)


Matrix-Vector Product:
 [[154]
 [ 90]
 [ 93]]


### task 14


In [23]:
A = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 1))
x = np.linalg.solve(A, b)
print("\nSolution to Ax = b:\n", x)


Solution to Ax = b:
 [[1.33898305]
 [0.61016949]
 [0.59322034]]


### task 15


In [24]:
matrix_5x5 = np.random.randint(0, 10, (5, 5))
row_sums = np.sum(matrix_5x5, axis=1)
column_sums = np.sum(matrix_5x5, axis=0)
print("\nRow-wise sums:", row_sums)
print("Column-wise sums:", column_sums)


Row-wise sums: [17 18 24 20 23]
Column-wise sums: [13 26 17 17 29]
